apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  namespace: kube-system
spec:
  selector:
    app: node-exporter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9100
