name: govulncheck

on:
  schedule:
    # Run every Monday
    - cron: '0 0 * * 1'

env:
  GO_VERSION: "^1.20"

jobs:
  ci-security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install govulncheck binary
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run security checks
        run: |
          govulncheck -v ./...
